name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      pr_url: ${{ steps.create_pr.outputs.pr_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Create version bump
        id: version
        run: |
          npx changeset version
          if git diff --quiet; then
            echo "No version changes. Skipping PR creation."
            exit 0
          fi

      - name: Commit version changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b changeset-release
          git add .
          git commit -m "chore: version packages"
          git push origin -u changeset-release

      - name: Create Pull Request
        id: create_pr
        run: |
          output=$(gh pr create -B main -H changeset-release -r ${{ github.actor }} \
          -t 'Release: Version Packages' -b 'Automated version bump using Changesets.' \
          -l release -l automated)
          echo "pr_url=${output}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
